import { GameState, PlayerType, StateMachineTransition } from "../types";

export const Player: Record<string, PlayerType> = {
  Black: "B",
  White: "W",
};

export const StateMachineValidTransitions: StateMachineTransition = {
  PENDING_INIT_ROLL: ["PENDING_ROLL"],
  PENDING_MOVE: ["PENDING_ROLL"],
  PENDING_ROLL: ["PENDING_ROLL", "PENDING_MOVE"],
  WIN: [],
};

export const INITIAL_STATE: GameState = {
  turn: undefined,
  diceRolled: [],
  positionTransitionsMap: [],
  stateMachine: "PENDING_INIT_ROLL",
  initDiceRolled: {
    W: -1,
    B: -1,
  },
  hitSpace: {
    W: 0,
    B: 0,
  },
  bearOff: {
    W: 0,
    B: 0,
  },
  pips: [
    { isEmpty: false, player: Player.Black, count: 2, pipId: 0 },
    { isEmpty: true, player: undefined, count: 0, pipId: 1 },
    { isEmpty: true, player: undefined, count: 0, pipId: 2 },
    { isEmpty: true, player: undefined, count: 0, pipId: 3 },
    { isEmpty: true, player: undefined, count: 0, pipId: 4 },
    { isEmpty: false, player: Player.White, count: 4, pipId: 5 },
    { isEmpty: true, player: undefined, count: 0, pipId: 6 },
    { isEmpty: false, player: Player.White, count: 3, pipId: 7 },
    { isEmpty: true, player: undefined, count: 0, pipId: 8 },
    { isEmpty: true, player: undefined, count: 0, pipId: 9 },
    { isEmpty: true, player: undefined, count: 0, pipId: 10 },
    { isEmpty: false, player: Player.Black, count: 5, pipId: 11 },
    { isEmpty: false, player: Player.White, count: 5, pipId: 12 },
    { isEmpty: true, player: undefined, count: 0, pipId: 13 },
    { isEmpty: true, player: undefined, count: 0, pipId: 14 },
    { isEmpty: true, player: undefined, count: 0, pipId: 15 },
    { isEmpty: false, player: Player.Black, count: 3, pipId: 16 },
    { isEmpty: true, player: undefined, count: 0, pipId: 17 },
    { isEmpty: false, player: Player.Black, count: 5, pipId: 18 },
    { isEmpty: true, player: undefined, count: 0, pipId: 19 },
    { isEmpty: true, player: undefined, count: 0, pipId: 20 },
    { isEmpty: true, player: undefined, count: 0, pipId: 21 },
    { isEmpty: true, player: undefined, count: 0, pipId: 22 },
    { isEmpty: false, player: Player.White, count: 2, pipId: 23 },
  ],
};

export const INITIAL_STATE_TEST: GameState = {
  turn: "W",
  diceRolled: [],
  initDiceRolled: {
    W: -1,
    B: -1,
  },
  positionTransitionsMap: [],
  stateMachine: "PENDING_ROLL",
  hitSpace: {
    W: 0,
    B: 0,
  },
  bearOff: {
    W: 0,
    B: 0,
  },
  // pips: [
  //   { isEmpty: false, player: Player.Black, count: 2, pipId: 0 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 1 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 2 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 3 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 4 },
  //   { isEmpty: false, player: Player.White, count: 4, pipId: 5 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 6 },
  //   { isEmpty: false, player: Player.White, count: 3, pipId: 7 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 8 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 9 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 10 },
  //   { isEmpty: false, player: Player.Black, count: 5, pipId: 11 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 12 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 13 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 14 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 15 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 16 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 17 },
  //   { isEmpty: false, player: Player.Black, count: 5, pipId: 18 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 19 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 20 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 21 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 22 },
  //   { isEmpty: false, player: Player.White, count: 2, pipId: 23 },
  // ],
  // pips: [
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 0 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 1 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 2 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 3 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 4 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 5 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 6 },
  //   { isEmpty: false, player: Player.Black, count: 2, pipId: 7 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 8 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 9 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 10 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 11 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 12 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 13 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 14 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 15 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 16 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 17 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 18 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 19 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 20 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 21 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 22 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 23 },
  // ],

  // pips: [
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 0 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 1 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 2 },
  //   { isEmpty: false, player: Player.White, count: 2, pipId: 3 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 4 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 5 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 6 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 7 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 8 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 9 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 10 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 11 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 12 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 13 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 14 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 15 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 16 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 17 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 18 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 19 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 20 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 21 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 22 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 23 },
  // ],

  pips: [
    { isEmpty: false, player: "W", count: 3, pipId: 0 },
    { isEmpty: false, player: "W", count: 4, pipId: 1 },
    { isEmpty: false, player: "W", count: 1, pipId: 2 },
    { isEmpty: true, player: undefined, count: 0, pipId: 3 },
    { isEmpty: true, player: undefined, count: 0, pipId: 4 },
    { isEmpty: true, player: undefined, count: 0, pipId: 5 },
    { isEmpty: true, player: undefined, count: 0, pipId: 6 },
    { isEmpty: true, player: undefined, count: 0, pipId: 7 },
    { isEmpty: true, player: undefined, count: 0, pipId: 8 },
    { isEmpty: true, player: undefined, count: 0, pipId: 9 },
    { isEmpty: true, player: undefined, count: 0, pipId: 10 },
    { isEmpty: true, player: undefined, count: 0, pipId: 11 },
    { isEmpty: true, player: undefined, count: 0, pipId: 12 },
    { isEmpty: true, player: undefined, count: 0, pipId: 13 },
    { isEmpty: true, player: undefined, count: 0, pipId: 14 },
    { isEmpty: true, player: undefined, count: 0, pipId: 15 },
    { isEmpty: true, player: undefined, count: 0, pipId: 16 },
    { isEmpty: true, player: undefined, count: 0, pipId: 17 },
    { isEmpty: false, player: "B", count: 2, pipId: 18 },
    { isEmpty: false, player: "B", count: 2, pipId: 19 },
    { isEmpty: false, player: "B", count: 2, pipId: 20 },
    { isEmpty: false, player: "B", count: 2, pipId: 21 },
    { isEmpty: false, player: "B", count: 1, pipId: 22 },
    { isEmpty: false, player: "B", count: 4, pipId: 23 },
  ],

  // pips: [
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 0 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 1 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 2 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 3 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 4 },
  //   { isEmpty: false, player: Player.Black, count: 2, pipId: 5 },
  //   { isEmpty: false, player: Player.Black, count: 1, pipId: 6 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 7 },
  //   { isEmpty: false, player: Player.Black, count: 1, pipId: 8 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 9 },
  //   { isEmpty: false, player: Player.Black, count: 1, pipId: 10 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 11 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 12 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 13 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 14 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 15 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 16 },
  //   { isEmpty: false, player: Player.Black, count: 1, pipId: 17 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 18 },
  //   { isEmpty: false, player: Player.Black, count: 5, pipId: 19 },
  //   { isEmpty: false, player: Player.Black, count: 2, pipId: 20 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 21 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 22 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 23 },
  // ],

  // pips: [
  //   { isEmpty: false, player: Player.White, count: 2, pipId: 0 },
  //   { isEmpty: false, player: Player.White, count: 5, pipId: 1 },
  //   { isEmpty: false, player: Player.White, count: 4, pipId: 2 },
  //   { isEmpty: false, player: Player.White, count: 2, pipId: 3 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 4 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 5 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 6 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 7 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 8 },
  //   { isEmpty: false, player: Player.White, count: 3, pipId: 9 },
  //   { isEmpty: false, player: Player.White, count: 1, pipId: 10 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 11 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 12 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 13 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 14 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 15 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 16 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 17 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 18 },
  //   { isEmpty: false, player: Player.Black, count: 5, pipId: 19 },
  //   { isEmpty: false, player: Player.Black, count: 2, pipId: 20 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 21 },
  //   { isEmpty: false, player: Player.Black, count: 3, pipId: 22 },
  //   { isEmpty: true, player: undefined, count: 0, pipId: 23 },
  // ],
};
